name: Build

on:
  push:
    tags:
      - '*'
    branches:
      - 'main'
  pull_request:
    branches:
      - 'main'

jobs:

  update-submodules:
    runs-on: windows-latest
    
    steps:
    - uses: actions/checkout@v4
    - name: update submodules 
      run: |
        git submodule update --init --recursive --remote
      shell: cmd
      
  build:
    needs: update-submodules
    runs-on: windows-2019
    strategy:
      matrix:
        configuration: [Release]
        platform: [x64, x86]

    steps:
    - uses: actions/checkout@v4
      with:
        submodules: 'recursive'

    - name: Add MSBuild to PATH
      uses: microsoft/setup-msbuild@v1.3.1
      with:
        vs-version: '16.0'

    - name: Build solution
      working-directory: ${{github.workspace}}
      run: |
        msbuild /m /p:Configuration=${{matrix.configuration}} /p:Platform=${{matrix.platform}} /p:PlatformToolset=v141_xp proxychains.exe.sln

    - name: Prepare release package
      shell: pwsh
      run: |
        $platform = "${{ matrix.platform }}"
        mkdir anon-proxy-win
        
        # Copy only the required files
        Copy-Item "win32_output/anon-proxy_$($platform).exe" "anon-proxy-win/anon-proxy_$($platform).exe"
        Copy-Item "win32_output/proxychains_hook_$($platform).dll" "anon-proxy-win/"
        Copy-Item "win32_output/anon-proxy-helper_win32_$($platform).exe" "anon-proxy-win/"

    - name: Upload artifacts
      uses: actions/upload-artifact@v4
      with:
        name: anon-proxy-win-${{ matrix.platform }}
        path: anon-proxy-win
        if-no-files-found: error

  release:
    runs-on: ubuntu-latest
    needs: [build]
    if: startsWith(github.ref, 'refs/tags/')
    steps:
      - name: Download artifacts
        uses: actions/download-artifact@v4
        with:
          path: artifacts/

      - name: Create release packages
        run: |
          mkdir -p release-artifacts/
          chmod +x artifacts/anon-proxy-win-*/*
          zip -j release-artifacts/anon-proxy-win-x64.zip artifacts/anon-proxy-win-x64/*
          zip -j release-artifacts/anon-proxy-win-x86.zip artifacts/anon-proxy-win-x86/*
          ls -la release-artifacts/

      - name: Create GitHub Release
        uses: ncipollo/release-action@v1
        with:
          artifacts: "release-artifacts/anon-proxy-win-*.zip"
